
# This file was *autogenerated* from the file u.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_4 = Integer(4)
Integer=int
a=_sage_const_1 
b=_sage_const_2 
c=_sage_const_4 
print(b**c)

